import "./globals.css"
import PageTransition from "../components/PageTransition";
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  )
}
